# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "bootstrap" do |atomic|
    atomic.vm.network "private_network", ip: "192.168.33.100"
    atomic.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
    atomic.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end

end