# -*- mode: ruby -*-
# vi: set ft=ruby :

$vm_memory = 2048
$vm_cpus = 1
$vm_info = [
  {name: "kube-master", ip: "192.168.33.101"},
  {name: "kube-node", ip: "192.168.33.102"},
]

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  $vm_info.each do |vm|
    config.vm.define vm[:name] do |atomic|
      atomic.vm.hostname = vm[:name]
      atomic.vm.network "private_network", ip: vm[:ip]
      atomic.vm.provider "virtualbox" do |vb|
        vb.cpus = $vm_cpus
        vb.memory = $vm_memory
      end
      atomic.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "ansible/playbook.yaml"
      end
    end
  end
end